// Pure list, safe to import from client components (no db or node imports).
/** Private mailbox activity must not be exposed by general team/platform audit feeds. */
export const MAILBOX_ACTIVITY_ACTIONS = [
  "mailbox.items_listed",
  "mailbox.item_read",
  "mailbox.draft_saved",
  "mailbox.send_approved",
  "mailbox.send_requested",
  "mailbox.item_trashed",
  "mailbox.item_restored",
  "mailbox.item_starred",
  "mailbox.item_unstarred",
  "mailbox.item_folder_changed",
  "mailbox.folder_created",
  "mailbox.folder_renamed",
  "mailbox.folder_archived",
] as const;
export type MailboxActivityAction = (typeof MAILBOX_ACTIVITY_ACTIONS)[number];

export const AUDIT_ACTIONS = [
  "api_key.created",
  "api_key.revoked",
  "api_key.renamed",
  "domain.created",
  "domain.verified",
  "domain.deleted",
  "mailbox.created",
  "mailbox.updated",
  "mailbox.granted",
  "mailbox.revoked",
  "mailbox.items_listed",
  "mailbox.item_read",
  "mailbox.draft_saved",
  "mailbox.message_classified",
  "mailbox.item_trashed",
  "mailbox.item_restored",
  "mailbox.item_starred",
  "mailbox.item_unstarred",
  "mailbox.item_folder_changed",
  "mailbox.folder_created",
  "mailbox.folder_renamed",
  "mailbox.folder_archived",
  "mailbox.agent_key_created",
  "mailbox.agent_key_revoked",
  "mailbox.send_queued",
  "mailbox.send_approved",
  "mailbox.send_requested",
  "mailbox.license_granted",
  "mailbox.license_revoked",
  "webhook.created",
  "webhook.updated",
  "webhook.secret_rotated",
  "webhook.deleted",
  "member.invited",
  "member.joined",
  "member.removed",
  "member.role_changed",
  "member.left",
  "invitation.revoked",
  "invitation.resent",
  "team.created",
  "team.deleted",
  "team.type_changed",
  "team.limits_updated",
  "team.broadcasts_paused",
  "team.broadcasts_resumed",
  "team.suspended",
  "team.reinstated",
  "team.send_review_held",
  "team.send_review_released",
  // The operator marked one of the team's domains as verified at the
  // customer SMTP relay's provider (or took the mark back).
  "team.domain_relay_enabled",
  "team.domain_relay_disabled",
  // The instance side of a break-glass content access (team_id null, so the
  // team's own audit can never show it); "content.accessed" is the row the
  // team gains seven days later, dated at the access.
  "content.revealed",
  "content.accessed",
  "console.flag_opened",
  "console.flag_cleared",
  "console.flag_reopened",
  "region.breaker_opened",
  "region.breaker_closed",
  "region.quota_requested",
  "instance.settings_updated",
  "instance.monitor_settings_updated",
  "instance.reserve_updated",
  "monitor.override_set",
  "monitor.override_cleared",
  "monitor.broadcasts_paused",
  "monitor.broadcasts_resumed",
  "support.view_started",
  "support.view_ended",
  "billing.checkout_started",
  "billing.portal_opened",
  "billing.subscription_updated",
  "billing.plan_changed",
  "billing.overage_toggled",
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];
